name: CI

on:
  push:

  pull_request:

  workflow_dispatch:

env:
  ENV_GKOSTIN: 1

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']
    services:
      apache:
        image: ghcr.io/mlibrary/dpact-bootstrap/apache:latest
        env:
	  ENV_GKOSTIN: 1
        ports:
          - 8080:8080/tcp
          - 8443:8443/tcp
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
        # change this to (see https://github.com/ruby/setup-ruby#versioning):
        # uses: ruby/setup-ruby@v1
        uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Wait For HTTP Service
        run: ./bin/wait-for-http-service http://localhost:8080
      - name: Run CI - lint { standard, rubocop } and tests { spec }
        run: bundle exec rake
