name: package-apache

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Package
        uses: craftech-io/package-action@v3.1.0
        id: url-GPR
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          context: ./image/apache
          dockerfile: ./image/apache/Dockerfile
          image_name: apache
          tags: |
            latest
#            ${{ github.sha }}
      - name: imageURL
        run: echo ${{ steps.url-GPR.outputs.imageURL }}
